esphome:
  name: esphome-web-9ea300
  friendly_name: Whole House Dehumidifier Control
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
    
  fast_connect: true
switch:
- platform: gpio
  pin: GPIO21
  name: "Fan" #K1 Relay 
  id: Fan
  
- platform: gpio 
  pin: GPIO19
  name: "Dehumidifier" #K2 Relay
  id: Dehumidifier
  
